// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGc2f9EhMCPZZogDws_TMC2BIC4rZiIo',
    appId: '1:276067846352:android:256a782f212d5efea2f6d5',
    messagingSenderId: '276067846352',
    projectId: 'liga-independente-app',
    storageBucket: 'liga-independente-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFViPyf6Dl8_cdovt-wM_c8c3vOTZ0D90',
    appId: '1:276067846352:ios:80fbc3dff5d4a2bca2f6d5',
    messagingSenderId: '276067846352',
    projectId: 'liga-independente-app',
    storageBucket: 'liga-independente-app.appspot.com',
    androidClientId: '276067846352-biqdchvkd4fduplc9lo2fl30rjlo4agu.apps.googleusercontent.com',
    iosClientId: '276067846352-okiqnuel0j35oj1261llqo9mkfjiiqeq.apps.googleusercontent.com',
    iosBundleId: 'com.creath.ligaapp.ligaIndependenteFrontend',
  );

}